#!/usr/bin/env python3

import sys

print("Welcome to MyShell")

help_string = '''
show_config
show_network
show_time
set_time
set_config
set_hostname
show_log
show_disk
show_ver
'''

command_table = {
    'show_config': '1',
    'show_network': '2',
    'show_time': '3',
    'set_time': '4',
    'set_config': '5',
    'set_hostname': '6',
    'show_log': '7',
    'show_disk': '8',
    'show_ver': '9',
    'help': help_string
}

while True:
    input_string = input('$')
    
    if input_string == 'quit':
        sys.exit(0)

    command = command_table.get(input_string, 'invaild command')
    print(command)

    
